### ISSUE TITLE
Illegal switch-statement in 2_2_0 pio_darray.c

### ISSUE THREAD

**Issue by cponder** [NCAR/ParallelIO#886] opened 2017-03-12 14:15 UTC
I'm trying to build PIO 2_2_0 with the PGI 16.10 compiler and OpenMPI 1.10.4. When compiling the file

            src/clib/pio_darray.c

I'm running into these errors

         PGC-S-0067-Switch expression must be of integer type (/cm/extra/apps/PIO/2_2_0/PGI-16.10_OpenMPI-1.10.4_HDF5-1.10.0-patch2_NetCDF-C-4.4.1_NetCDF-F-4.4.4/distro/src/clib/pio_darray.c: 465)
         PGC-S-0091-Integer constant expression required (/cm/extra/apps/PIO/2_2_0/PGI-16.10_OpenMPI-1.10.4_HDF5-1.10.0-patch2_NetCDF-C-4.4.1_NetCDF-F-4.4.4/distro/src/clib/pio_darray.c: 468)
         PGC-S-0093-Type cast required for this conversion of constant (/cm/extra/apps/PIO/2_2_0/PGI-16.10_OpenMPI-1.10.4_HDF5-1.10.0-patch2_NetCDF-C-4.4.1_NetCDF-F-4.4.4/distro/src/clib/pio_darray.c: 468)
         PGC-W-0093-Type cast required for this conversion of constant (/cm/extra/apps/PIO/2_2_0/PGI-16.10_OpenMPI-1.10.4_HDF5-1.10.0-patch2_NetCDF-C-4.4.1_NetCDF-F-4.4.4/distro/src/clib/pio_darray.c: 468)

If I read correctly, the switch-statement is using a pointer as the selector

     465             switch (vtype)
     466             {
     467             case MPI_BYTE:
     468                 fill = &byte_fill;
     469                 break;
     470             case MPI_CHAR:

and the cases are likewise pointers, declared in mpi.h:

     326 typedef struct ompi_communicator_t *MPI_Comm;
     327 typedef struct ompi_datatype_t *MPI_Datatype;
     328 typedef struct ompi_errhandler_t *MPI_Errhandler;

     309 #if !OMPI_BUILDING
     310 #define OMPI_PREDEFINED_GLOBAL(type, global) ((type) ((void *) &(global)))
     311 #else
     312 #define OMPI_PREDEFINED_GLOBAL(type, global) ((type) &(global))
     313 #endif 

    1044 #define MPI_BYTE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_byte)
    1045 #define MPI_PACKED OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_packed)
    1046 #define MPI_CHAR OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_char)

My understanding of the C standard is that the selector needs to be an Integer type, and adding an (int) typecast might be enough to fix line 465, but the cases don't look to me like they really resolve at compiletime, which is also in the specification.

**Comment by cponder** [comment] 2017-03-12 14:19
I didn't have this problem with the Intel compiler. I haven't tried GCC but expect you've probably been using it for testing yourselves. Likely these compilers are extending the standard in this regard while the PGI compiler is more strict.

I never liked the restriction to compiletime cases, I think the expectation was that the compiler would use some clever indexing to jump to the correct case (as opposed to compiling into a sequence of if's), but doubt this was ever used to any advantage.

**Comment by cponder** [comment] 2017-03-12 14:22
I'm working with MPAS-A and would like to be able to use it with PIO2, given that the PIO2 install includes some regression-tests that I can use as a sanity-check.
This is going to take some effort, though: with the Intel compiler, the MPAS-A is giving me compiletime errors that I need to resolve with the developers.

**Comment by edhartnett** [comment] 2017-03-12 16:12
I believe I can give you a fix, hampered somewhat by the fact that I don't have access to a PGI compiler.

But I am not sure I understand the problem.

The variable in question is not a pointer, but a MPI_Datatype. In my version of MPI (mpich) that is typedef'd to be an int.

In your version of MPI it is a pointer? I don't see how that even works. Can you look in your mpi.h and see what MPI_Datatype is defined as?

**Comment by jedwards4b** [comment] 2017-03-12 17:44
I'm afraid we don't test enough with openmpi - we need to add an openmpi test to our nightlies.

**Comment by edhartnett** [comment] 2017-03-14 13:56
OK, I've installed openmpi on my machine, and can reproduce the failure.

When I simply cast to int, I get a different compile time error, which makes sense because I am just casting a pointer to int and that's not going to be helpful.

But how are you supposed to compare against MPI types in openmpi? I changed it to the following if statement:

```
            if (vtype == MPI_BYTE)
                fill = &byte_fill;
            else if (vtype == MPI_CHAR)
                fill = &char_fill;
            else if (vtype == MPI_SHORT)
                fill = &short_fill;
            else if (vtype == MPI_INT)
                fill = &int_fill;
            else if (vtype == MPI_FLOAT)
                fill = &float_fill;
            else if (vtype == MPI_DOUBLE)
                fill = &double_fill;
#ifdef _NETCDF4
            else if (vtype == MPI_UNSIGNED_CHAR)
                fill = &ubyte_fill;
            else if (vtype == MPI_UNSIGNED_SHORT)
                fill = &ushort_fill;
            else if (vtype == MPI_UNSIGNED)
                fill = &uint_fill;
            else if (vtype == MPI_LONG_LONG)
                fill = &int64_fill;
            else if (vtype == MPI_UNSIGNED_LONG_LONG)
                fill = &uint64_fill;
#endif /* _NETCDF4 */
            else
                return pio_err(ios, file, PIO_EBADTYPE, __FILE__, __LINE__);

```

(And actually I like this change because it is less lines of code this way.)

Now the code builds, but I am getting multiple test failures. :-(

If one of you openmpi users could tell me if I am comparing the types correctly, that would be helpful.

**Comment by jedwards4b** [comment] 2017-03-14 14:25
I think that this comparison is correct - is it clear that the test failures are related to this and not some other issue in openmpi?

**Comment by edhartnett** [comment] 2017-03-14 15:14
No, not at all clear. I have no investigated the failures yet at all, but I will do so and get back to you.

**Comment by edhartnett** [comment] 2017-03-14 18:27
OK, at least part of the problem is that I have to rebuild everything with openmpi. ;-) I am doing that now.

**Comment by edhartnett** [comment] 2017-03-16 11:06
The problem in this ticket has been fixed.

I'm still struggling to get openmpi working on my machine, but openmpi will continue under another ticket. I am going to close this one.

**Closed by edhartnett** 2017-03-16 11:06 UTC
Labels: bug
