### ISSUE TITLE
Fixing "duplicate" files in PIO global file list

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#99] opened 2016-08-26 19:57 UTC
PIO uses a global file list, pio_file_list (pio_lists.c), to keep track of 
files. This list is currently indexed using the file id (file handle) and 
the current code implicitly assumes that file handles for files are
unique globally (across all MPI processes).
However this assumption is not true when performing file operations
across multiple communicators (PIO iosystems). This issue results
in duplicate (same file id) file_desc_t entries in the global file list
in certain scenarios.

**Comment by jayeshkrishna** [comment] 2016-08-26 19:58
The jayeshkrishna/pio2/fix_dup_files_in_pio_file_list branch has two tests (pio_iosystem_test[2]) that show the issues resulting from the assumption above.

**Comment by jayeshkrishna** [comment] 2016-08-26 20:01
One of the issues is already fixed in the branch ( jayeshkrishna/pio2/fix_dup_files_in_pio_file_list ).
The overall solution that I propose (to fix all issues) is to index the global PIO file list using both file id and the communicator. This involves changing the C interface of most of the PIO functions (minor change but touches a lot of code).
@jedwards4b / @edhartnett / @Katetc : Please let me know your thoughts.

**Comment by jayeshkrishna** [comment] 2016-08-26 20:05
On the branch ( jayeshkrishna/pio2/fix_dup_files_in_pio_file_list ), pio_iosystem_test.F90 passes (the branch has a fix for the issue identified by this test) and pio_iosystem_test2.F90 fails/hangs due to the issue that I have mentioned above.

**Comment by edhartnett** [comment] 2016-08-26 20:16
I think the answer is to retain the ncids provided by the underlying libraries, but to add an internal ncid that is assigned to each ncid/communicator combination. This achieves the indexing you desire.

Then there need be no change of the C API. The user will still keep track of things with an ncid.

**Comment by jedwards4b** [comment] 2016-08-26 20:17
I'm not sure I understand why this would change the c interface - wouldn't it just change the calculation of the fh value based on communicator which is already available inside the routines?

**Comment by jayeshkrishna** [comment] 2016-08-27 04:51
IMO, changing the C interface to allow the fortran interface to pass the iosysid should allow us to search to search the list with ncid+iosysid. Adding another internal ncid might be complicating the design.

**Comment by edhartnett** [comment] 2016-08-27 11:30
Adding another internal ncid is necessary for other reasons. The parallel-netcdf library and the netCDF classic library will start overlapping ncids after the first 3 parallel-netcdf files are open. (parallel-netcdf uses 0 for it's first ncid, then increments. NetCDF classic starts with 3.)

I was planning on adding an internal ncid after I finish the asynch work.

Can you be specific about which C functions you want to change the API for?

**Comment by jayeshkrishna** [comment] 2016-08-29 15:05
Any PIO function (C function) that accesses the global list needs to now search it based on ncid and the iosysid (and many functions search the global list). So the iosysid has to be passed to these functions from the Fortran interface.
I remember seeing the discussion on why @edhartnett was proposing PIO-internal ncids,is Issue #80 the right one to look at? Would incorporating the library (netcdf*/pnetcdf/...) in the search process fix this issue (Or in another way, why/how does PIO get confused with duplicate ncids)?

**Comment by edhartnett** [comment] 2016-08-29 16:10
Replacing the ncid with internally-generated ncids would accomplish what you wish. Each internal ncid can be associated with an iosysid, without changing the APIs.

I think changing the API to the extent proposed would be a mistake. The API is already in use - making changes is costly.

**Comment by jayeshkrishna** [comment] 2016-08-29 16:38
I agree, changing the C API may be costly.
However I do feel that we should fix the bug the right way (rather than patch it for the sake of backward compatibility). IMO, passing an opaque handle to user (pio_file) is the "right" thing to do. This would allow us to optimize searching these global file lists, have a cleaner cleanup :) and catch invalid uses, user bugs, effectively (trying to read a closed file etc.). This can complicate the Fortran-C interface though.
 One of the issues that I see with PIO1 is that it does not give enough information to the user when things fail (especially new code with user bugs). I am planning to address this in a different issue.
Creating internal ncids comes with its own set of management code (using smarter C++ data structures can solve some issues),
* How do we reclaim ncids?
* What is the limits/size of the array structure used to store the ids?
* Can we detect user bugs where they operate on closed/deleted files?

However using an internal PIO id, similar to netcdf id, makes it easier for users transitioning from the netcdf world. And we could use a similar strategy to netcdf to implement these internal PIO ids.

(Note: I am open to fixing this issue in any way the whole team decides.)

**Comment by jayeshkrishna** [comment] 2016-09-02 15:20
@edhartnett / @jedwards4b / @Katetc : If you already have a design to use PIO file ids I am ok with going ahead with @edhartnett 's solution (if everyone else is ok with it). We can go ahead and merge the changes in this branch (I will create a new branch - merging master and this branch) and @edhartnett can add PIO file ids. Please let me know your thoughts.
@edhartnett : When (estimate) can you finish the implementation of PIO file ids?

**Comment by rljacob** [comment] 2016-09-02 15:40
If the C-API is only used internally, I think this should be done as Jayesh suggested.

**Comment by edhartnett** [comment] 2016-09-14 15:02
The C API should not be changed. This is a strong library convention that should not be violated.

@jayeshkrishna to answer your question I hope to merge code shortly, and then we can convert fully to the async version of the code. Right now I am tracking down a tricky finalize bug that happens when I have more than one computational component. Unfortunately the NCAR multi-cores workshop is going on and I am attending that, at least partially. ;-)

**Comment by jayeshkrishna** [comment] 2016-09-14 15:12
Thanks @edhartnett . No problem, I will wait for your merge (Since this merge is big, and changes source files etc, you might also want to consider checking it in as long as it does not break any existing features - if the bug is minor. This would help me with my work on fixing dup entries in the file list.).

Another point to consider is why we don't want the C API changed at this stage of development? Is it already used by others (outside PIO)? Please note that the C API does not have an exact mapping with the fortran versions (and I agree that the fortran versions of the API that have existed for a while should not change).

**Comment by rljacob** [comment] 2016-09-14 15:51
There's nothing intrinsically wrong with changing an API.   Its disruptive but that can be managed by understanding who is disrupted and communicating the changes and their schedule.

**Comment by edhartnett** [comment] 2016-09-16 18:05
When I check out master and build it (without async), the new test pio_iosystem_tests2 hangs for me with the following output:

mpiexec -n 4 ./pio_iosystem_tests2
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 PIO_TF: Starting three_files_two_iosystems_odd_even
PIO_TF:  Testing : PNETCDF                                                                                             
0 Setting IO buffer size on all iotasks to 10485760
0 Setting IO buffer size on all iotasks to 10485760
0 Setting IO buffer size on all iotasks to 10485760
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
 val = pio_iosys_test_file2.nc, fname =pio_iosys_test_file2.nc
 val = pio_iosys_test_file2.nc, fname =pio_iosys_test_file2.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
 val = pio_iosys_test_file2.nc, fname =pio_iosys_test_file2.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
 val = pio_iosys_test_file2.nc, fname =pio_iosys_test_file2.nc
PIO_TF:  Testing : NETCDF                                                                                              
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file0.nc, fname =pio_iosys_test_file0.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
 val = pio_iosys_test_file1.nc, fname =pio_iosys_test_file1.nc
  C-c C-c

Is this test passing for everyone else?

**Comment by jayeshkrishna** [comment] 2016-09-16 18:11
Yes, that is the new test that shows the remaining bug (it is supposed to hang and timeout for now) to be fixed in PIO

**Comment by edhartnett** [comment] 2016-09-16 18:24
OK, awesome. I will just comment it out on my branch to get the build working again so I can merge code...

**Comment by jedwards4b** [comment] 2016-09-18 13:23
So the test pio_iosystem_tests2 demonstrates the problem in this issue?   And it will be fixed when we merge in the async code without changing the API?

**Comment by jayeshkrishna** [comment] 2016-09-19 13:32
No, pio_iosystem_tests2 demonstrates a different problem that is not fixed by the merge of the async code. Changing the API touches a lot of code including the async code and I wanted to get the async (at least the first cut) code merged before I start my branch (so we can merge the branch). 
I have started working on the fix on a branch from the current master and will use it as a reference for a new branch from master after the async merge.

**Comment by jedwards4b** [comment] 2016-09-19 16:37
Before you put in a lot of time on this let's settle the issue of how to fix it - can we do it and maintain the current system of integer file handles?

**Comment by jayeshkrishna** [comment] 2016-09-19 16:47
No, the issue here is that a file is only uniquely defined by the file id (netcdf id from lower level library), the communicator and the lower level filesystem type .
The fix I am proposing is to use opaque file handles, like we have for the fortran interface , that can encapsulate this information (I am planning to return pointers to the file_desc structure that already contains this info).
Another related area we need to fix is the async code that explicitly transmits this info (currently only the flie id -which should be fixed to pass all the relevant info).

**Comment by edhartnett** [comment] 2016-09-19 17:25
Instead, let's use an internally defined ncid, just as netCDF does. 

The ncid, defined at the PIO level, is all that will be needed to definitively identify the iosysid, the netCDF flavor/format, and the file. There is no need to change the C API to achieve this.

**Comment by jedwards4b** [comment] 2016-09-19 17:41
I would prefer to use integer id's and not change the APi if possible - what is the algorithm to determine the internal ncid?

**Comment by jayeshkrishna** [comment] 2016-09-19 17:42
As I discussed before using an opaque file handle has its benefits. Why do we want to use an internally defined ncid?
Also, I am not sure if it is easy to create globally (across MPI_COMM_WORLD) unique file ids. Just curious, how would you go about generating these globally unique ids?

**Comment by edhartnett** [comment] 2016-09-19 17:54
Using integer IDs is very much preferable in the C API. Other languages (ex. python) can easily use C APIs as long as they stick to simple parameters.

Changing the C API should obviously be avoided. It makes a lot of extra work.

Let me take a stab at demonstrating what I mean. As soon as the current merge is complete I will take a branch and attempt to solve this issue without changing the C API. I will put my work up on a pull request and you guys can take a look...

**Comment by jedwards4b** [comment] 2016-09-19 18:40
Ed - I think that maybe we should start by just proposing an algorithm and trying to poke holes in it.

**Comment by edhartnett** [comment] 2016-09-19 18:48
If we add a new field to file_desc_t, int pio_ncid, which is our internally generated ncid, then we change pio_get_file_from_id() to use pio_ncid, instead of fh, to identify the file,

Then we add a global int in pio_lists.c called current_pio_ncid, initializing it to 1. As files are opened, we assign current_pio_ncid++ to the pio_ncid of the file_desc_t struct.

This means that all tasks would get the same ncid. Internally the fh may be different on different processes if that is how pnetcdf wants to roll. Each process will use the fh it got from the base library, whatever that might be.

The iosystemid is already in the file_desc_t struct, so isn't that all we need? Or am I missing something?

**Comment by jedwards4b** [comment] 2016-09-19 19:05
The iosysid knows about the current comp comm and io comm, but not necessarily about MPI_COMM_WORLD - so we won't necessarily have all tasks have the same value for pio_ncid since comp comms can overlap.

**Comment by edhartnett** [comment] 2016-09-19 19:11
But all tasks that participate in that io_comm will have the same pio_ncid.

comp_comms that overlap will be running two different computation tasks, right? Each will have to open the file, and each will get a different pio_ncid, but that will be OK because the IO component is keeping track of the IDs.

**Comment by jedwards4b** [comment] 2016-09-19 19:58
I think that this works if current_pio_ncid is a component of the iosystem_desc_t

**Comment by edhartnett** [comment] 2016-09-19 20:27
Yes, I get what you are saying. You're correct, we must have a current ID for each iosysid, or else the IO tasks will get out of sync and come up with different numbers.

**Comment by jedwards4b** [comment] 2016-09-19 20:45
Jayesh - do you see any reason this proposal won't work?

**Comment by jayeshkrishna** [comment] 2016-09-19 20:53
What about processes that belong to two (or more) iosystems ?

**Comment by edhartnett** [comment] 2016-09-19 21:09
Another alterrnative would be to have the IO tasks maintain the list of ncid, and pass back an ncid to the open and create calls.

**Comment by jayeshkrishna** [comment] 2016-09-19 21:20
Not sure if I understood the last suggestion completely. But, aren't we complicating the logic here? 
We need to find a match by using ncid + iosysid + filesystem type . Trying to maintain the current C API is resulting in more complicated logics, IMO.

**Comment by jedwards4b** [comment] 2016-09-20 01:24
I think that this got broken in commit 458a3fa and that test pio_iosystem_tests2 would work in commits prior to that one.

**Comment by edhartnett** [comment] 2016-09-20 20:22
I am trying to understand pio_iosystem_tests2. 

It is run on 4 processors. 

In function PIO_TF_Init_ we call PIO_Init, which calls PIO_Init_Intracomm, which creates an intracomm for the WORLD. 

We then split the processors into two communicators, even and odd. 

You do a PIO_Init, which takes you to PIO_Init_Intracomm. From that we get another iosysid, which gets put into odd_even_iosys.

Then we use pio_tf_iosystem_ as the iosysid for the create_file calls. So we are using all 4 processes to create the 3 files.

Then all 4 processes check file 0, the first sample file.

The even processes check file 1 and odd proceses check file 2. Then they check them again.

Did I get that correct?

**Comment by jedwards4b** [comment] 2016-09-20 20:43
I think that's correct and what you see happening is that the lookup for file id in the last step gets confused and is trying to check the wrong file.

**Comment by edhartnett** [comment] 2016-09-21 20:31
I believe I have a replica of this issue in a C-only test. It's on my current branch, ejh_ncid_issue, and the test is tests/unit/test_iosystem2.c.

**Comment by jedwards4b** [comment] 2016-09-21 20:39
That file doesn't exist in the branch - did you forget to push?

**Comment by edhartnett** [comment] 2016-09-21 20:58
Sorry, try again...

**Comment by jedwards4b** [comment] 2016-09-21 21:57
Got it now - you have one comment there that says "run async tests" but this is not an async test, correct?  It looks like the call to open_and_check_file at line 180 should use newcomm and not MPI_COMM_WORLD?

**Comment by jedwards4b** [comment] 2016-09-21 22:01
Also on that line file1 should be file

**Comment by edhartnett** [comment] 2016-09-22 15:04
I have made the changes you suggest in the test program. However, none of them change the result, which is that this code hangs. ;-) I am working on fixing that...

**Comment by edhartnett** [comment] 2016-09-28 16:28
On branch ejh_ncid_issue you can see the changes required to fix the repeating ncid issue. The issue is that each iosystem gets it's own executable of whatever netCDF base library is being used. As a result, opening a file on each of two different iosystems will result in the same ncid being provided in each case.

The change is to add a new field, pio_ncid, to the file_desc_t struct, and assign a PIO generated ncid for every open/create. 

This does require many code changes, because ncid and file->fh are no longer equivalent, and sometimes pio_ncid and other times fh must be used. However no API changes are required.

The original test provided by @jayeshkrishna is not yet working on this branch. Somewhere I did not catch the conversion correctly - I'm working on that today. But my simpler C tests are now passing.

**Comment by jayeshkrishna** [comment] 2016-09-28 16:37
@edhartnett : Also please take a look at the new test, pio_iosystem_tests3.F90, that demonstrates another scenario that results in dup file ids. Both pio_iosystem_tests2 and pio_iosystem_tests3 need to pass (both hang with master now - and works with pio1)

**Comment by edhartnett** [comment] 2016-09-28 16:46
Yes, will do.

**Comment by edhartnett** [comment] 2016-09-30 13:52
On my branch, ejh_ncid_issues, the pio_iosystem_test2 is now passing. But I had to comment out the MPI_Barrier call or else it hangs. Not sure what is going on there, and I would appreciate any feedback on that. 

My next step will me merging in the current master to get the new test and see how that does...

**Comment by jayeshkrishna** [comment] 2016-09-30 15:05
Maybe rebase is better (than merging master)

**Comment by edhartnett** [comment] 2016-10-04 15:30
OK, I see that pio_iosystem_test3 is using 3 communicators, a world communicator with 0, 1, 2, and 3, an even communicator, with 0, 2, and an overlap communicator with 0, 1, 3.

I am attempting to produce a simplified C version of this test in tests/unit/test_iosystem3.c on my current branch...

**Comment by edhartnett** [comment] 2016-10-12 15:48
An update as to how the code on the ncid_issue branch works.

I have introduced pio_ncid, which is what is now used for all ncid's in the PIO api. The underlying library ncid is kept in the fh field.

The pio_ncid is assigned at file creating or open. It starts at 16 and increments by one. There is no attempt to use the same pio_ncid on different tasks. If task 0 is involved in more file creations than other processors, it will be using a different pio_ncid. But that all works out as long as the calling program is using the ncid it receives.

(Incidentally I have also found that HDF5 parallel does the same thing as pnetcdf - it can use different file ids on different processes. So there is no longer any attempt to Bcast the fh. Whatever each task gets for a fh, that's what it uses.)

**Comment by jayeshkrishna** [comment] 2016-10-14 21:45
@edhartnett : It looks like your changes in ejh_ncid_issue gets pio_iosystem_test3 to pass too. I just tried your branch and it looks like you have not picked some changes in the testing framework, causing the fortran test, pio_iosystem_test3, to hang (Did you cherry pick just the pio_iosystem_test3 test?).
Try merging your branch locally to master and running the tests.

**Comment by edhartnett** [comment] 2016-10-14 22:44
OMG I am about to burst into tears with happiness. That pio_iosystem_test3 was driving me nuts. I had a C program that was an exact duplicate of the PIO calls, which passes, and yet pio_iosystem_test3 failed...

I rebased master just a few days ago, but perhaps I messed it up. I will try again on Monday morning and see if I can get a working test, then I can put up a PR before our meeting.

Thanks for the good news! ;-)

**Comment by edhartnett** [comment] 2016-10-18 22:02
I believe we can finally close this issue, right?

**Comment by edhartnett** [comment] 2016-10-22 12:00
@jayeshkrishna any objection if I now close this issue?

**Comment by jayeshkrishna** [comment] 2016-10-22 12:27
This issue can now be closed. The last issue mentioned here was fixed in cdc9e09c17bc6f51ac95d8b7c7710544305140b1

**Closed** 2016-10-22 12:35 UTC
Labels: bug
