### ISSUE TITLE
pio_decomp_frame_tests fails with latest netCDF

### ISSUE THREAD

**Issue by edhartnett** [NCAR/ParallelIO#1265] opened 2018-01-04 13:57 UTC
Running against the latest netCDF I get this failure in pio_decomp_frame_tests. Doh!

  ```
   PIO_TF:Test 18: nc_test_limited_time_dim_PIO_double_real  ------  PASSED
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Read in prof_inparm namelist from: gptl.nl
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf) Using profile_disable= F  profile_timer=           4
 (t_initf)  profile_depth_limit=       99999  profile_detail_limit=           1
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 (t_initf)  profile_barrier= F  profile_outpe_num=           0
 (t_initf)  profile_outpe_stride=           1  profile_single_file= F
 (t_initf)  profile_global_stats= T  profile_papi_enable= F
 PIO_TF: Testing : PIO_REARR_BOX
 PIO_TF: Starting nc_write_read_4d_col_decomp_PIO_int_integer__
PIO_TF:  Testing : PIO_int : PNETCDF                                                                                             
PIO_TF:  Testing : PIO_int : NETCDF                                                                                              
PIO_TF:  Testing : PIO_int : NETCDF4C                                                                                            
PIO_TF:  Testing : PIO_int : NETCDF4P                                                                                            
  C-c C-c[mpiexec@mikado] Sending Ctrl-C to processes as requested
```

**Comment by jedwards4b** [comment] 2018-05-22 13:22
100% tests passed, 0 tests failed out of 31

I am using gnu-7.3.0, openmpi-3.0.1, netcdf-4.6.1, hdf5-1.10.1

**Comment by edhartnett** [comment] 2018-05-22 13:23
Your netcdf and hdf5 are built with parallel I/O?

**Comment by jedwards4b** [comment] 2018-05-22 13:29
Yes - using openmpi-3.0.1

**Comment by edhartnett** [comment] 2018-05-22 13:36
Do you have mpich?

**Comment by jedwards4b** [comment] 2018-05-22 13:41
So Carl Ponder is reporting this same failure:
```
(built with PGI 18.4 & OpenMPI 3.0.1) on our internal NVIDIA DGX cluster with GPFS
```
I don't think that it's an mpi library problem.

**Comment by jedwards4b** [comment] 2018-05-22 19:22
I don't know how to help, I haven't been able to reproduce these problems.

**Comment by cponder** [comment] 2018-05-22 20:55
I tried it on our PSG cluster and got these fails:

      The following tests FAILED:
	       21 - test_darray_multivar (Failed)
	       23 - test_darray_multivar3 (Failed)
	       24 - test_darray_1d (Failed)
	       25 - test_darray_3d (Failed)
	       89 - pio_decomp_frame_tests (Timeout)

The first four may be due to the NFS fileystem or the fact that I'm using OpenMPI 1.10.7 instead of 3.1.0.
But the 89 is failing similarly with GPFS on our other cluster, and the decomp tests 45-88 & 90 all passed, so I'm guessing that NFS is not the problem with 89 on PSG.

**Comment by cponder** [comment] 2018-05-23 15:06
JIm -- also -- if you could run your build & test on a PSG/hsw_p100 node, and the problem goes away, I will try reproducing your steps.

**Comment by jedwards4b** [comment] 2018-05-23 15:34
//Details about finding NetCDF_C
FIND_PACKAGE_MESSAGE_DETAILS_NetCDF_C:INTERNAL=[/glade/u/home/jedwards/netcdf-4.6.1/openmpi/3.0.1/gnu/7.3.0/lib/libnetcdf.so][/glade/u/home/jedwards/netcdf-4.6.1/openmpi/3.0.1/gnu/7.3.0//include][v()]

**Comment by jedwards4b** [comment] 2018-05-23 15:35
@cponder didn't I already do that?

**Comment by cponder** [comment] 2018-05-23 15:38
I knew you were working on the Power nodes with the XL compiler, but couldn't tell if you'd worked on the Intel nodes.
Do you have your build-scripts and log files of the PIO passing the test?
I can try adjusting my build to see if I can get it to work.

**Comment by jedwards4b** [comment] 2018-05-25 16:43
I'm now able to reproduce the problem.   I see that all 4 tasks are entering the call to 
nc_get_vara_int but only task 0 is getting to this message in the hdf5 library:
```before coming to final collective IO```
this is apparently working for other datatypes but fails for INT.  (are we on the same page?)

**Comment by edhartnett** [comment] 2018-05-25 16:46
I don't know that it works for other datatype, but I am also using NC_INT in my test.

**Comment by jedwards4b** [comment] 2018-05-25 16:52
I think that's an important piece of information - it seems to be working for NC_DOUBLE.

**Comment by jedwards4b** [comment] 2018-05-25 17:38
At line 932 of HDFmpio.c (HDF v1.10.1) num_chunk==1 for task 0 and 0 for all other tasks.  There is a collective operation inside that loop which then causes an mpi hang.

**Comment by cponder** [comment] 2018-05-25 17:56
Is this a problem in the HDF5? 1.10.2 is the latest release.

**Comment by jedwards4b** [comment] 2018-05-25 19:41
No - HDF v1.10.2 fails in the same way.

**Comment by jedwards4b** [comment] 2018-05-25 19:58
It looks to me like a bug in hdf5.   Looking at the v1.10.2 source the conditional at line 1157 and the comment at line 1283 imply that some tasks will participate in one branch and others in the other branch, however the call at line 1289 leads to a collective MPI_Bcast where all of the tasks are expected to land.

**Comment by cponder** [comment] 2018-05-26 16:28
Can you guys raise this to the HDF5 people (help@hdfgroup.org)?
If they can spin a fixed version, or make a patch, I'd be happy to try it.
My PNetCDF builds all pass their regressions, but I'm always seeing the same small set of regression-failures with my HDF5 & NetCDF builds in every version & configuration I've tried, I'm wondering if this is the root cause.

**Comment by edhartnett** [comment] 2018-05-27 17:27
I will prepare a HDF5 test program for netCDF which tries to capture this error.

Jim I can do the release at any time, let me know.

**Comment by cponder** [comment] 2018-06-01 08:17
Ed -- given the nature of the HDF5 bug, do you think you could come up with a patch to the HDF5 instead, so we don't have to (temporarily) mess up the PIO code?

**Comment by edhartnett** [comment] 2018-06-01 10:16
That would be great. I am working on this bug but stuck waiting for netCDF.

**Comment by jedwards4b** [comment] 2018-06-04 13:33
I think that this morning we have an example that produces the problem without using pio, we also have a suggested workaround (or fix?) from the hdf5 people I should be able to try today.

**Comment by cponder** [comment] 2018-06-04 13:40
That's great news! And I can test the patch to see if it helps with the HDF5 & NetCDF C/F regressions.
Also, I'm in boulder for the 10 days for a Hack-a-Thon plus the WRF/MPAS-A workshop.
Would you guys have time to meet in the afternoon on Friday (4/8)?
I could make time on another day if you prefer.

**Comment by jedwards4b** [comment] 2018-06-04 22:15
the example had a bug and after I fixed the bug I couldn't reproduce the problem, so I'm still working on it, but gaining a much better understanding of the issue.

**Comment by jedwards4b** [comment] 2018-06-06 16:31
I've created a branch isolate_netcdf4_issue in which the pio_decomp_frame_tests runs only the problem case.

**Comment by cponder** [comment] 2018-06-08 03:09
There's a bug filed with the HDF5 developers, right?
I'd like to be able to track this, can you give me a link to it?
I'm hoping it will get fixed in the HDF5 release.
I've been seeing failures in the HDF5 & NetCDF C/F regressions and hope that this will improve.

**Comment by cponder** [comment] 2018-06-08 17:29
Also when will you post the next PIO release tarball?

**Comment by edhartnett** [comment] 2018-06-08 20:29
Great! I will add this to netcdf as a test...

**Comment by jedwards4b** [comment] 2018-06-08 20:30
Thanks - I've also sent it to the hdf5 help desk.

**Comment by gsjaardema** [comment] 2018-08-10 02:15
Can someone tell me the HDF5 issue number or bug report related to this.  Since it affects NetCDF I think I might be able to get some priority on it.  

I am seeing somethIn similar with repeated calls to nc_sync that may be hitting the same issue.

**Comment by jedwards4b** [comment] 2018-08-10 12:31
@gsjaardema HDFFV-10501 (Bug in HDF5 1.10.2 parallel when some processes do not have data to write)

**Comment by edwardhartnett** [comment] 2020-08-26 13:12
I believe everything related to this issue has been fixed.

**Closed by edwardhartnett** 2020-08-26 13:12 UTC
