### ISSUE TITLE
test_darray_async does not fail gracefully 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ParallelIO#1287] opened 2018-03-08 22:45 UTC
When an error is encountered in the check results loop at line 101 of test_darray_async.c the io task hangs and the test cannot proceed.

**Comment by edhartnett** [comment] 2018-05-04 15:49
The problem here is general. If one of the IO tasks in async mode encounters an error, it shuts down, but the non-IO tasks have no idea what is going on.

The problem is, how can the IO tasks send a message? We send messages the other way, and the IO tasks is listening for them, but the computation tasks are not listening for messages.

**Comment by edwardhartnett** [comment] 2020-09-11 12:03
I'm going to close this issue since I can't think of any way to fix it. If you can think of one, please let me know.

**Closed by edwardhartnett** 2020-09-11 12:03 UTC
Labels: bug, tests
