### ISSUE TITLE
Fortran version of pio_deletefile does not return an error code

### ISSUE THREAD

**Issue by jayeshkrishna** [NCAR/ParallelIO#281] opened 2016-12-06 16:07 UTC
Although the C interface for pio_deletefile (pioc_deletefile) returns an error code the fortran version does not. This is a bug and needs to be fixed.

@dqwu noted this issue in Issue #276

**Comment by jedwards4b** [comment] 2016-12-06 18:03
This should be a simple change and this function call is generally not used by applications I think that the impact of the api change would be minimal.

**Comment by gold2718** [comment] 2016-12-06 19:16
I can confirm that CAM does not use this interface.
The upcoming DESP and DART models may well use this interface but dealing with the change will not be a problem.

**Comment by edwardhartnett** [comment] 2021-01-22 16:11
@jedwards4b since this is in the Fortran API, I've assigned it to you. If you want to just close it, that's fine by me. The deletefile function is hardly every used anyway, as far as I know, and there's no much anyone can do on error.

**Closed** 2022-01-10 16:10 UTC
Labels: bug
